### ISSUE TITLE
Potential bug in estimation of M ratio with low counts

### ISSUE THREAD

**Issue by Max-Lovell** [metacoglab/HMeta-d#21]
Hi,

I wanted to point out something I've come across that might not be ideal functioning. Admittedly, the task I'm running had some design issues resulting in non-ideal messy data, but it might be of interest nonetheless. Running the following numbers fit_meta_d_mcmc([0,0,5,1],[0,0,0,6]) results in a d1=0, meta_d=2.2047, but an M-ratio of M_ratio: 2.2047e+04. My dataset records a few such cases. 

If it's a bug I understand a solution might take some time to implement, but if you have any idea of under what conditions or why this happens, that'd be greatly appreciated as I may be able to do something on my end if so.

Thanks,

Max

**Comment by smfleming** [comment]
Hi Max,

Apologies for the delay in getting to this.
I don't think this is a bug - it's the way the code should be working. Fitting a single-subject meta-d to only 12 trials is highly underconstrained and not advised (with 2 confidence levels, you need sufficient trials for coverage of the 2x2(stim)x2(response) matrix of counts, ie several multiples of 8 trials (I would view ~80 as a minimum here). Hierarchical estimation can help of course and we explore this for fewer trial numbers (down to ~40 per subject) in the NOC paper. But even there, I would not go much below 50 per subject.

Anyway, for the code - what's happening here is that d' is exactly zero because at the midpoint of the type 1 ROC, hit and false alarm rates are equal (it would be worth checking whether there might be a bug here? the entries in the vectors suggest that whenever S1 is shown, an error is made, but when S2 is shown, the response is always correct - and these balance out. See https://github.com/metacoglab/HMeta-d/wiki/HMeta-d-tutorial).

Meta-d is non zero as confidence is lower for incorrect (S1 stim) than correct (S2 stim) responses. You can see this by running metad_visualise on a fit object in the workspace. M_ratio (meta-d/d) should then be infinite, but the reason you get the value you do is because of this line:

`d1_samples(d1_samples == 0) = 0.0001;   % avoid divide-by-zero issue for samples of exactly zero`

As I mentioned, these are all nonsensical values as the parameters are underconstrained by having very few trials. But I think it's working as it should do.

cheers
Steve
